version: '3.9'

services:
  db:
    image: postgres:latest
    hostname: db
    environment:
        POSTGRES_PASSWORD: "sample"
        POSTGRES_USER: "sample"
        POSTGRES_DB: "sample"
    volumes:
      - sample-data:/var/lib/postgresql/data
    ports:
      - 55432:5432
 
volumes:
  sample-data:
    name: sample-data